### ISSUE TITLE
Ponle las anotaciones JPA

### ISSUE THREAD

**Issue by Lainezz** [frademuca/ProyectoStockControl#1]
https://github.com/frademuca/ProyectoStockControl/blame/a8e4fb334f3531b30971137116be24705fce5e50/src/main/java/com/es/stockcontrol/model/Producto.java#L5

Pon todas las anotaciones JPA.

**Comment by frademuca** [comment]
Completado

**Comment by Lainezz** [comment]
En el atributo fecha_alta, ponle la anotación @ Temporal

**Comment by frademuca** [comment]
Añadida @Temporal
