### ISSUE TITLE
Si ha habido error, devuelve el user igualmente?

### ISSUE THREAD

**Issue by Lainezz** [frademuca/ProyectoStockControl#3]
https://github.com/frademuca/ProyectoStockControl/blob/a8e4fb334f3531b30971137116be24705fce5e50/src/main/java/com/es/stockcontrol/repository/UserRepository.java#L24

Si ha habido una excepción, el método está devolviendo user como si nada hubiera pasado. ¿No debería devolver null... u otra cosa?

**Comment by legolegolegolego** [comment]
Solucionado en commit: "solucionado create return"
